services:
  composition-blueprint-engine:
    image: quay.io/jupyter/pytorch-notebook:cuda12-python-3.11
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0', '1', '2']
            capabilities: [gpu]
    container_name: composition-blueprint-engine
    ports:
      - "8000:8888"